### ISSUE TITLE
docker-compose.yaml ksqldb-server-ccloud config refers to /etc/ksql should be /etc/ksqldb

### ISSUE THREAD

**Issue by eric-asuncion** [confluentinc/confluent-hybrid-cloud-workshop#47]
Should be:
      KSQL_CONFIG_DIR: "/etc/ksqldb"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksqldb/log4j-rolling.properties"

**Comment by gianlucanatali** [comment]
Thank you @eric-asuncion , I will fix this
